[package]
name = "fms"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8"
chardetng = "0.1"
async-std = { version = "1.12", features = ["attributes"] }
regex = "1.10"
clap = { version = "4", features = ["derive"] }
